### ISSUE TITLE
PA Review: Photos

### ISSUE THREAD

**Issue by Kelby2** [Kelby2/pxlgram#12]

**Comment by mashuDuek** [comment]
Hi,
 
All photos need to be the same size. when we are in user show page. 

Need to fix your temp logout button, to finally make it to what its supposed to be. 

The "caption" (this will be a great photo) is not good enough right now. 

Let me know when you've made those changes and I'll take a look at it again. 

Mashu

**Comment by Kelby2** [comment]
Hey Mashu,

Per our conversation, the photos are okay. The logout button is in the current user profile so I had to set that up first. Let me know if anything more needs to be done for the photo MVP!
